name: Release

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.sr_github_token }}
          NPM_TOKEN: ${{ secrets.sr_npm_token }}
